name: Lint

on:
  pull_request:
    paths:
      - '**.py'        # only trigger if a .py file is changed
      - 'pyproject.toml'  # optional: trigger if black config changes too

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          use_pyproject: true
